language: python
dist: xenial
sudo: true

language: python

# Limit git depth to speed up build
git:
  depth: 5

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=lint
    - python: 3.8
      env: TOXENV=documents

addons:
  apt:
    packages:
      - aspell
      - aspell-en

install:
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov

deploy:
  - provider: pypi
    user: facelessuser
    server: https://upload.pypi.org/legacy/
    password:
      secure: tp4E9eyoZKwx97ChpL6cxEcCm8A5PA6qb3cMLmp/RAbDJSTiXKcKTxiVM7N16CuqeQ70Eb76uRY6BaAYNtgymIItRCDCvKvgYEC1d1p7cRGoGzuCZ/LMhEOOk88kKPLMQ2ZYGC4v2Lx8UqTBW7mu6qqKl6DajUEmObygfhgdFF+q6LWFzZOEPhCdTnOIDQHUAHIusQ7tKmM3UwmHl/EgxcVGAc5Jicg8OT17enqm7ESZ7Lqifodm4zAWeh2j0Sv8U4P54x1WOjG+0hYlko7qsZ9YtjHpQWn6VL4qarVko6/zV/h3OPe5VPcvv8UdoeP7lDLdKkc5AYHaqvdfqf9+fSwE01v59UWpQNwBAMWPiMjddLto/VHOENQvhez4sZTIfq7RmMTUnZrQDB8PYlPUfm8inwzUHtB72JO52gh9lGtfdsSCDzb3eaLxgf2Zr8NtXKbj1sMmnAN8SDT4BRiON1pdJROfNJG/qoZ7coRVqRZeZkSPXifU/yvmKJY/x/EG/1YrugYlGqJSo7uyZdF3FEQAVVgs+O/P2hAMwVXJnShfnk9q+X1elqxipx8rrTTd4kmCxwf7v9DOtSsKftRUoRFvvyf2p4YtSwqom8mAqYv3LHL96fegpw5oYoiutIhZRQTt4oxl9G1qQ62m3KfB5FneEc2Rw2F/TR99tRtfyHY=
    distributions: "sdist bdist_wheel"
    skip_upload_docs: true
    on:
      tags: true
      repo: facelessuser/pep562
      condition: "$TOXENV = documents"
